### ISSUE TITLE
Fix variable action output usage

### ISSUE THREAD

**Issue by a2** [a2/shortcuts-swift#4]
Currently it's annoying to have to add a parameter to functions that have action output. It would be nicer to chain on `Action`.

Before:

```swift
var batteryLevel = Variable.actionOutput()
let shortcut = buildShortcut(
    getBatteryLevel(&batteryLevel)
)
```

After:

```swift
var batteryLevel = Variable.actionOutput()
let shortcut = buildShortcut(
    getBatteryLevel().savingOutput(to: &batteryLevel)
)
```

**Comment by alexaubry** [comment]
Another way we could tackle this issue is having a protocol for saving the output of an action to a variable that can be used in addition to the `ActionContainer` protocol when creating actions.

```swift
public typealias ActionWithOutput = ActionContainer & ActionOutputProviding

public protocol ActionOutputProviding {
    func savingOutput(to variable: UnsafePointer<Variable>) -> ActionContainer
}
```

`Action` would conform to this protocol, and return the updated action:

```swift
extension Action: ActionOutputProviding {
    public func savingOutput(to variable: UnsafePointer<Variable>) -> ActionContainer {
        let parameters = withActionOutput(parameters: self.parameters, output: variable)
        return Action(identifier: self.identifier, parameters: parameters)
    }
}
```

We would use that protocol on the function definition, to inform the caller that the returned action has an output:

```swift
public func text(_ text: String) -> ActionWithOutput {
    return Action(...)
}
```

Where outputs are not supported, we return a regular action container:

```swift
public func conditional(...) -> ActionContainer {
    return Action(...)
}

public func sendEmail(...) -> ActionContainer {
    return Action(...)
}
```

The information about output compatibility is provided after creating the action, and lost after the output is saved, which means that users in the builder can use the `saveOutput` method without interfering with chaining:

- if I want to save the output, I call `savingOutput` and use the result as a normal action container
- if I don't care about the output, the action can be chained as a normal action container
- I cannot chain multiple `savingOutput` calls (unsupported in Shortcuts)
- I cannot call `savingOutput` if the action does not support output
